import { blockType } from "../../types";
import About from "./About";
import Artist from "./Artist";
import Caution from "./Caution";
import ImgSlide from "./ImgSlide";
import News from "./News";
import Organizer from "./Organizer";
import Place2 from "./Place2";
import Placebox from "./Placebox";
import Program from "./Program";
import Share from "./Share";
import TimeTable from "./TimeTable";
import TopView from "./TopView";

export const layoutArr: blockType[] = [
  {
    name: "topViewLayout",
    displayName: "トップ画面",
    jsx: TopView,
    defaultText: [
      "サブタイトル",
      "イベントタイトル",
      "キャッチコピー",
      "が入ります。",
    ],
    defaultColor: [""],
    defaultFont: [""],
    defaultSize: [""],
    defaultImage: [""],
  },
  {
    name: "newsLayout",
    displayName: "ニュース",
    jsx: News,
    defaultText: ["NEWS", "2020.9.5", "○○を公開しました！"],
    defaultColor: [""],
    defaultFont: [""],
    defaultSize: [""],
    defaultImage: [""],
  },
  // {
  //   name: "imgSlideLaytout",
  //   displayName:"トップ画面",
  //   jsx: ImgSlide,
  //   defaultText: [],
  //   defaultColor: [""],
  //   defaultFont: [""],
  //   defaultSize: [""],
  // },
  {
    name: "placeboxLayout",
    displayName: "開催場所",
    jsx: Placebox,
    defaultText: [
      "幕張メッセ　展示ホール○～○階",
      "〒123-4567 ○○市△△区2-1",
      "【Web】www.a-bcdef.co.jp",
      "日程： 2018年8月11日(土)〜",
      "15日(水)・17日(金)〜19日(日)",
    ],
    defaultColor: [""],
    defaultFont: [""],
    defaultSize: [""],
    defaultImage: [""],
  },
  {
    name: "organizerLayout",
    displayName: "主催者紹介",
    jsx: Organizer,
    defaultText: [
      "○○　○○○○",
      "主催者の紹介文が入ります。主催者の紹介文が入ります。主催者の紹介文が入ります。主催者の紹介文が入ります。ここは後で差し替えます。",
    ],
    defaultColor: [""],
    defaultFont: [""],
    defaultSize: [""],
    defaultImage: [""],
  },
  {
    name: "AboutLayout",
    displayName: "イベント概要",
    jsx: About,
    defaultText: [
      "「イベントタイトル」とは？",
      "サンプルテキストです。サンプルテキストです。",
      "サンプルテキストです。サンプルテキストです。",
    ],
    defaultColor: [""],
    defaultFont: [""],
    defaultSize: [""],
    defaultImage: [""],
  },
  {
    name: "ProgramLayout",
    displayName: "プログラム",
    jsx: Program,
    defaultText: [
      "プログラムタイトル",
      "プログラム1の説明が入ります。",
      "プログラムタイトル",
      "プログラム2の説明が入ります。",
      "プログラムタイトル",
      "プログラム3の説明が入ります。",
      "プログラムタイトル",
      "プログラム4の説明が入ります。",
    ],
    defaultColor: [""],
    defaultFont: [""],
    defaultSize: [""],
    defaultImage: [""],
  },
  {
    name: "TimeTableLayout",
    displayName: "タイムテーブル",
    jsx: TimeTable,
    defaultText: [
      "タイムテーブル",
      "STAGE1",
      "artist",
      "artist",
      "artist",
      "10:00",
      "11:00",
      "12:00",
      "13:00",
      "14:00",
      "15:00",
      "16:00",
      "17:00",
      "18:00",
      "19:00",
      "STAGE2",
      "artist",
      "artist",
      "artist",
    ],
    defaultColor: [""],
    defaultFont: [""],
    defaultSize: [""],
    defaultImage: [""],
  },
  {
    name: "artist",
    displayName: "登壇者紹介",
    jsx: Artist,
    defaultText: [
      "アーティスト",
      "アーティスト1",
      "アーティストの説明が入ります。アーティストの説明が入ります。",
      "アーティスト2",
      "アーティストの説明が入ります。アーティストの説明が入ります。",
      "アーティスト3",
      "アーティストの説明が入ります。アーティストの説明が入ります。",
    ],
    defaultColor: [""],
    defaultFont: [""],
    defaultSize: [""],
    defaultImage: [""],
  },
  {
    name: "place2",
    displayName: "開催場所2",
    jsx: Place2,
    defaultText: [
      "幕張メッセ　展示ホール〇～〇階",
      "住所：〒123-4567 ○○市△△区2-1",
      "Web：www.a-bcdef.co.jp",
      "TEL:：000-0000-0000",
    ],
    defaultColor: [""],
    defaultFont: [""],
    defaultSize: [""],
    defaultImage: [""],
  },
  {
    name: "caution",
    displayName: "注意事項",
    jsx: Caution,
    defaultText: [
      "注意事項",
      "注意事項1が入ります。",
      "注意事項2が入ります。",
      "注意事項3が入ります。",
      "サンプルテキストです。",
      "この文章は後で差し替えます。",
    ],
    defaultColor: [""],
    defaultFont: [""],
    defaultSize: [""],
    defaultImage: [""],
  },
  {
    name: "SHARE",
    displayName: "SNS共有ボタン",
    jsx: Share,
    defaultText: [],
    defaultColor: [],
    defaultFont: [],
    defaultSize: [],
    defaultImage: [""],
  },
];
